__all__ = [
    "SQL",
    "SQL_FUNC",
    "SQL_TYPES",
    "SQL_TYPES_EXTENDED",
    "SQL_FUNC_PRAGMA",
    "SQL_FUNC_PRAGMA_EXTENDED",
]

from enum import StrEnum, auto
from dataclassdb.utils import UpperStrEnum


class SQL(UpperStrEnum):
    ABORT = auto()
    ACTION = auto()
    ADD = auto()
    AFTER = auto()
    ALL = auto()
    ALTER = auto()
    ALWAYS = auto()
    ANALYZE = auto()
    AND = auto()
    AS = auto()
    ASC = auto()
    ATTACH = auto()
    AUTOINCREMENT = auto()
    BEFORE = auto()
    BEGIN = auto()
    BETWEEN = auto()
    BY = auto()
    CASCADE = auto()
    CASE = auto()
    CAST = auto()
    CHECK = auto()
    COLLATE = auto()
    COLUMN = auto()
    COMMIT = auto()
    CONFLICT = auto()
    CONSTRAINT = auto()
    CREATE = auto()
    CROSS = auto()
    CURRENT = auto()
    CURRENT_DATE = auto()
    CURRENT_TIME = auto()
    CURRENT_TIMESTAMP = auto()
    DATABASE = auto()
    DEFAULT = auto()
    DEFERRABLE = auto()
    DEFERRED = auto()
    DELETE = auto()
    DESC = auto()
    DETACH = auto()
    DISTINCT = auto()
    DO = auto()
    DROP = auto()
    EACH = auto()
    ELSE = auto()
    END = auto()
    ESCAPE = auto()
    EXCEPT = auto()
    EXCLUDE = auto()
    EXCLUSIVE = auto()
    EXISTS = auto()
    EXPLAIN = auto()
    FAIL = auto()
    FILTER = auto()
    FIRST = auto()
    FOLLOWING = auto()
    FOR = auto()
    FOREIGN = auto()
    FROM = auto()
    FULL = auto()
    GENERATED = auto()
    GLOB = auto()
    GROUP = auto()
    GROUPS = auto()
    HAVING = auto()
    IF = auto()
    IGNORE = auto()
    IMMEDIATE = auto()
    IN = auto()
    INDEX = auto()
    INDEXED = auto()
    INITIALLY = auto()
    INNER = auto()
    INSERT = auto()
    INSTEAD = auto()
    INTERSECT = auto()
    INTO = auto()
    IS = auto()
    ISNULL = auto()
    JOIN = auto()
    KEY = auto()
    LAST = auto()
    LEFT = auto()
    LIKE = auto()
    LIMIT = auto()
    MATCH = auto()
    MATERIALIZED = auto()
    NATURAL = auto()
    NO = auto()
    NOT = auto()
    NOTHING = auto()
    NOTNULL = auto()
    NULL = auto()
    NULLS = auto()
    OF = auto()
    OFFSET = auto()
    ON = auto()
    OR = auto()
    ORDER = auto()
    OTHERS = auto()
    OUTER = auto()
    OVER = auto()
    PARTITION = auto()
    PLAN = auto()
    PRAGMA = auto()
    PRECEDING = auto()
    PRIMARY = auto()
    PRIMARY_KEY = auto()  # Manually adding PRIMARY KEY
    QUERY = auto()
    RAISE = auto()
    RANGE = auto()
    RECURSIVE = auto()
    REFERENCES = auto()
    REGEXP = auto()
    REINDEX = auto()
    RELEASE = auto()
    RENAME = auto()
    REPLACE = auto()
    RESTRICT = auto()
    RETURNING = auto()
    RIGHT = auto()
    ROLLBACK = auto()
    ROW = auto()
    ROWS = auto()
    SAVEPOINT = auto()
    SELECT = auto()
    SET = auto()
    STORED = auto()  # https://sqlite.org/gencol.html
    TABLE = auto()
    TEMP = auto()
    TEMPORARY = auto()
    THEN = auto()
    TIES = auto()
    TO = auto()
    TRANSACTION = auto()
    TRIGGER = auto()
    UNBOUNDED = auto()
    UNION = auto()
    UNIQUE = auto()
    UPDATE = auto()
    USING = auto()
    VACUUM = auto()
    VALUES = auto()
    VIEW = auto()
    VIRTUAL = auto()
    WHEN = auto()
    WHERE = auto()
    WINDOW = auto()
    WITH = auto()
    WITHOUT = auto()

    INTEGER = auto()
    TEXT = auto()
    BLOB = auto()
    REAL = auto()
    NUMERIC = auto()
    ANY = auto()  # FOR STRICT TABLE

    OLD = auto()  # Added to support CreateTrigger Queries https://www.sqlite.org/lang_createtrigger.html


class SQL_FUNC(StrEnum):
    # https://sqlite.org/lang_corefunc.html
    ABS = auto()
    CHANGES = auto()
    CHAR = auto()
    COALESCE = auto()
    CONCAT = auto()
    CONCAT_WS = auto()
    FORMAT = auto()
    GLOB = auto()
    HEX = auto()
    IF = auto()
    IFNULL = auto()
    IIF = auto()
    INSTR = auto()
    LAST_INSERT_ROWID = auto()
    LENGTH = auto()
    LIKE = auto()
    LIKELIHOOD = auto()
    LIKELY = auto()
    LOAD_EXTENSION = auto()
    LOWER = auto()
    LTRIM = auto()
    MAX = auto()
    MIN = auto()
    NULLIF = auto()
    OCTET_LENGTH = auto()
    PRINTF = auto()
    QUOTE = auto()
    RANDOM = auto()
    RANDOMBLOB = auto()
    REPLACE = auto()
    ROUND = auto()
    RTRIM = auto()
    SIGN = auto()
    SOUNDEX = auto()
    SQLITE_COMPILEOPTION_GET = auto()
    SQLITE_COMPILEOPTION_USED = auto()
    SQLITE_OFFSET = auto()
    SQLITE_SOURCE_ID = auto()
    SQLITE_VERSION = auto()
    SUBSTR = auto()
    SUBSTRING = auto()
    TOTAL_CHANGES = auto()
    TRIM = auto()
    TYPEOF = auto()
    UNHEX = auto()
    UNICODE = auto()
    UNISTR = auto()
    UNISTR_QUOTE = auto()
    UNLIKELY = auto()
    UPPER = auto()
    ZEROBLOB = auto()

    # https://sqlite.org/lang_aggfunc.html
    AVG = auto()
    GROUP_CONCAT = auto()
    MEDIAN = auto()
    PERCENTILE = auto()
    PERCENTILE_CONT = auto()
    PERCENTILE_DISC = auto()
    STRING_AGG = auto()
    SUM = auto()
    TOTAL = auto()
    COUNT = auto()

    # https://sqlite.org/lang_datefunc.html
    DATE = auto()
    TIME = auto()
    DATETIME = auto()
    JULIANDAY = auto()
    UNIXEPOCH = auto()
    STRFTIME = auto()
    TIMEDIFF = auto()

    INTEGER = auto()
    TEXT = auto()
    BLOB = auto()
    REAL = auto()
    NUMERIC = auto()
    ANY = auto()  # FOR STRICT TABLE


class SQL_TYPES(StrEnum):
    # https://sqlite.org/datatype3.html
    # https://sqlite.org/stricttables.html
    INTEGER = auto()
    TEXT = auto()
    BLOB = auto()
    REAL = auto()
    NUMERIC = auto()
    ANY = auto()  # FOR STRICT TABLE


class SQL_TYPES_EXTENDED(UpperStrEnum):
    INTEGER = auto()
    TEXT = auto()
    BLOB = auto()
    REAL = auto()
    NUMERIC = auto()
    ANY = auto()  # FOR STRICT TABLE
    INT = auto()
    TINYINT = auto()
    SMALLINT = auto()
    MEDIUMINT = auto()
    BIGINT = auto()
    UNSIGNED_BIG_INT = auto()
    INT2 = auto()
    INT8 = auto()
    CHARACTER = auto()
    VARCHAR = auto()
    VARYING_CHARACTER = auto()
    NCHAR = auto()
    NATIVE_CHARACTER = auto()
    NVARCHAR = auto()
    CLOB = auto()
    DOUBLE = auto()
    DOUBLE_PRECISION = auto()
    FLOAT = auto()
    DECIMAL = auto()
    BOOLEAN = auto()
    DATE = auto()
    DATETIME = auto()


class SQL_FUNC_PRAGMA(StrEnum):
    # https://sqlite.org/pragma.html
    ANALYSIS_LIMIT = auto()
    APPLICATION_ID = auto()
    AUTO_VACUUM = auto()
    AUTOMATIC_INDEX = auto()
    BUSY_TIMEOUT = auto()
    CACHE_SIZE = auto()
    CACHE_SPILL = auto()
    CELL_SIZE_CHECK = auto()
    CHECKPOINT_FULLFSYNC = auto()
    COLLATION_LIST = auto()
    COMPILE_OPTIONS = auto()
    DATA_VERSION = auto()
    DATABASE_LIST = auto()
    DEFER_FOREIGN_KEYS = auto()
    ENCODING = auto()
    FOREIGN_KEY_CHECK = auto()
    FOREIGN_KEY_LIST = auto()
    FOREIGN_KEYS = auto()
    FREELIST_COUNT = auto()
    FULLFSYNC = auto()
    FUNCTION_LIST = auto()
    HARD_HEAP_LIMIT = auto()
    IGNORE_CHECK_CONSTRAINTS = auto()
    INCREMENTAL_VACUUM = auto()
    INDEX_INFO = auto()
    INDEX_LIST = auto()
    INDEX_XINFO = auto()
    INTEGRITY_CHECK = auto()
    JOURNAL_MODE = auto()
    JOURNAL_SIZE_LIMIT = auto()
    LEGACY_ALTER_TABLE = auto()
    LEGACY_FILE_FORMAT = auto()
    LOCKING_MODE = auto()
    MAX_PAGE_COUNT = auto()
    MMAP_SIZE = auto()
    MODULE_LIST = auto()
    OPTIMIZE = auto()
    PAGE_COUNT = auto()
    PAGE_SIZE = auto()
    PRAGMA_LIST = auto()
    QUERY_ONLY = auto()
    QUICK_CHECK = auto()
    READ_UNCOMMITTED = auto()
    RECURSIVE_TRIGGERS = auto()
    REVERSE_UNORDERED_SELECTS = auto()
    SECURE_DELETE = auto()
    SHRINK_MEMORY = auto()
    SOFT_HEAP_LIMIT = auto()
    SYNCHRONOUS = auto()
    TABLE_INFO = auto()
    TABLE_LIST = auto()
    TABLE_XINFO = auto()
    TEMP_STORE = auto()
    THREADS = auto()
    TRUSTED_SCHEMA = auto()
    USER_VERSION = auto()
    WAL_AUTOCHECKPOINT = auto()
    WAL_CHECKPOINT = auto()


class SQL_FUNC_PRAGMA_EXTENDED(StrEnum):
    # https://sqlite.org/pragma.html
    # Non-Standard and testing commands
    PARSER_TRACE = auto()
    SCHEMA_VERSION = auto()
    STATS = auto()
    VDBE_ADDOPTRACE = auto()
    VDBE_DEBUG = auto()
    VDBE_LISTING = auto()
    VDBE_TRACE = auto()
    WRITABLE_SCHEMA = auto()
