name: "Build and test"
on: push

jobs:
  build-and-test:
    name: 
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        python-versions:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
            python-version: ${{ matrix.python-versions }}
            cache: 'pip'
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest tests --cov=src
        
      - name: Build package
        run: uv build

      - name: Smoke test (inline import)
        run: |
          uv run --with dist/*.whl --no-project -- python -c "import dataclassdb; print('Smoke test passed!')"
      - name: Smoke test (wheel)
        run: uv run --isolated --no-project --with dist/*.whl python tests/smoke_test.py
      - name: Smoke test (source distribution)
        run: uv run --isolated --no-project --with dist/*.tar.gz python tests/smoke_test.py


      - name: Upload artifact distributions
        uses: actions/upload-artifact@v4
        with:
          # Use unique artifact names per OS to avoid overwriting files
          name: pypi-artifacts-${{ matrix.python-versions }}
          path: dist/*

  publish-pypi:
    name: Publish to PyPI
    needs: [build-and-test] # Ensures publishing only happens if all builds succeed
    runs-on: ubuntu-latest

    steps:
      - name: Download all built artifacts
        uses: actions/download-artifact@v4
        with:
          # Merges all OS-specific directories back into a single dist/ folder
          path: dist
          pattern: pypi-artifacts-*
          merge-multiple: true